# For testing spring security stuff with another DB, h2 in mem configured to Postgres Mode

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgresSQL;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
