spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/moviedb"
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  security:
    user:
      name: dummy
      password: dummy
